import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import PageWrapper from "./PageWrapper"; // Import PageWrapper

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LeadConvert",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <PageWrapper>{children}</PageWrapper> {/* Wrap pages in animations */}
        </body>
      </html>
    </ClerkProvider>
  );
}
